# Generated by Django 5.2.5 on 2025-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Optional: Upload a PDF or other document.', null=True, upload_to='lesson_resources/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional: Upload a video file directly.', null=True, upload_to='lesson_videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: A URL to a video on YouTube, Vimeo, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Main description or content for the lesson.'),
        ),
    ]
